version: '2'

services:

  postgres-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "studzzy"
      POSTGRES_PASSWORD: "57udzzy@123#"
    ports:
    - "5432:5432"
    networks:
      - pg-net

  postgres-pgadmin4:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@studzzy.com"
      PGADMIN_DEFAULT_PASSWORD: "57udzzy@123#"
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "True"
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 10
    ports:
    - "5050:80"
    depends_on:
      - postgres-db
    networks:
      - pg-net


networks:
  pg-net:
    driver: bridge